INSERT INTO PARCO (nome, regione) VALUES
('Parco Nazionale delle Dolomiti Bellunesi', 'Veneto'),
('Parco Naturale Regionale della Lessinia', 'Veneto'),
('Parco Regionale dei Colli Euganei', 'Veneto'),
('Parco Naturale Regionale del Fiume Sile', 'Veneto'),
('Parco Regionale del Delta del Po', 'Veneto'),
('Parco Naturale Regionale delle Dolomiti d''Ampezzo', 'Veneto'),
('Nessun Parco', 'Veneto'),
('Nessun Parco', 'Trentino-Alto Adige'),
('Nessun Parco', 'Friuli-Venezia Giulia'),
('Parco Naturale Paneveggio - Pale di San Martino', 'Trentino-Alto Adige'),
('Parco Naturale Tre Cime', 'Trentino-Alto Adige'),
('Parco dell''Alto Garda Bresciano', 'Lombardia'),
('Parco del Mincio', 'Lombardia'),
('Parco Naturale Regionale delle Dolomiti Friulane', 'Friuli-Venezia Giulia');